package it.gov.fermitivoli.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CIRCOLARE_DB.
 */
public class CircolareDB {

    private Long id;
    /** Not-null value. */
    private java.util.Date dataInserimento;
    /** Not-null value. */
    private java.util.Date data;
    private int numero;
    /** Not-null value. */
    private String titolo;
    private String testo;
    private long token;
    /** Not-null value. */
    private String url;
    private boolean flagContenutoLetto;
    /** Not-null value. */
    private String key;

    public CircolareDB() {
    }

    public CircolareDB(Long id) {
        this.id = id;
    }

    public CircolareDB(Long id, java.util.Date dataInserimento, java.util.Date data, int numero, String titolo, String testo, long token, String url, boolean flagContenutoLetto, String key) {
        this.id = id;
        this.dataInserimento = dataInserimento;
        this.data = data;
        this.numero = numero;
        this.titolo = titolo;
        this.testo = testo;
        this.token = token;
        this.url = url;
        this.flagContenutoLetto = flagContenutoLetto;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getDataInserimento() {
        return dataInserimento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDataInserimento(java.util.Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

    /** Not-null value. */
    public java.util.Date getData() {
        return data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData(java.util.Date data) {
        this.data = data;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    /** Not-null value. */
    public String getTitolo() {
        return titolo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    public String getTesto() {
        return testo;
    }

    public void setTesto(String testo) {
        this.testo = testo;
    }

    public long getToken() {
        return token;
    }

    public void setToken(long token) {
        this.token = token;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public boolean getFlagContenutoLetto() {
        return flagContenutoLetto;
    }

    public void setFlagContenutoLetto(boolean flagContenutoLetto) {
        this.flagContenutoLetto = flagContenutoLetto;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

}
