package it.gov.fermitivoli.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import it.gov.fermitivoli.dao.CacheFileDBDao;
import it.gov.fermitivoli.dao.CircolareDBDao;
import it.gov.fermitivoli.dao.TermineDBDao;
import it.gov.fermitivoli.dao.NewsDBDao;
import it.gov.fermitivoli.dao.CircolareContieneTermineDBDao;
import it.gov.fermitivoli.dao.NewsContieneTermineDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 20160317): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 20160317;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CacheFileDBDao.createTable(db, ifNotExists);
        CircolareDBDao.createTable(db, ifNotExists);
        TermineDBDao.createTable(db, ifNotExists);
        NewsDBDao.createTable(db, ifNotExists);
        CircolareContieneTermineDBDao.createTable(db, ifNotExists);
        NewsContieneTermineDBDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CacheFileDBDao.dropTable(db, ifExists);
        CircolareDBDao.dropTable(db, ifExists);
        TermineDBDao.dropTable(db, ifExists);
        NewsDBDao.dropTable(db, ifExists);
        CircolareContieneTermineDBDao.dropTable(db, ifExists);
        NewsContieneTermineDBDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CacheFileDBDao.class);
        registerDaoClass(CircolareDBDao.class);
        registerDaoClass(TermineDBDao.class);
        registerDaoClass(NewsDBDao.class);
        registerDaoClass(CircolareContieneTermineDBDao.class);
        registerDaoClass(NewsContieneTermineDBDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
