package it.gov.fermitivoli.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import it.gov.fermitivoli.dao.CacheFileDB;
import it.gov.fermitivoli.dao.CircolareDB;
import it.gov.fermitivoli.dao.TermineDB;
import it.gov.fermitivoli.dao.NewsDB;
import it.gov.fermitivoli.dao.CircolareContieneTermineDB;
import it.gov.fermitivoli.dao.NewsContieneTermineDB;

import it.gov.fermitivoli.dao.CacheFileDBDao;
import it.gov.fermitivoli.dao.CircolareDBDao;
import it.gov.fermitivoli.dao.TermineDBDao;
import it.gov.fermitivoli.dao.NewsDBDao;
import it.gov.fermitivoli.dao.CircolareContieneTermineDBDao;
import it.gov.fermitivoli.dao.NewsContieneTermineDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheFileDBDaoConfig;
    private final DaoConfig circolareDBDaoConfig;
    private final DaoConfig termineDBDaoConfig;
    private final DaoConfig newsDBDaoConfig;
    private final DaoConfig circolareContieneTermineDBDaoConfig;
    private final DaoConfig newsContieneTermineDBDaoConfig;

    private final CacheFileDBDao cacheFileDBDao;
    private final CircolareDBDao circolareDBDao;
    private final TermineDBDao termineDBDao;
    private final NewsDBDao newsDBDao;
    private final CircolareContieneTermineDBDao circolareContieneTermineDBDao;
    private final NewsContieneTermineDBDao newsContieneTermineDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheFileDBDaoConfig = daoConfigMap.get(CacheFileDBDao.class).clone();
        cacheFileDBDaoConfig.initIdentityScope(type);

        circolareDBDaoConfig = daoConfigMap.get(CircolareDBDao.class).clone();
        circolareDBDaoConfig.initIdentityScope(type);

        termineDBDaoConfig = daoConfigMap.get(TermineDBDao.class).clone();
        termineDBDaoConfig.initIdentityScope(type);

        newsDBDaoConfig = daoConfigMap.get(NewsDBDao.class).clone();
        newsDBDaoConfig.initIdentityScope(type);

        circolareContieneTermineDBDaoConfig = daoConfigMap.get(CircolareContieneTermineDBDao.class).clone();
        circolareContieneTermineDBDaoConfig.initIdentityScope(type);

        newsContieneTermineDBDaoConfig = daoConfigMap.get(NewsContieneTermineDBDao.class).clone();
        newsContieneTermineDBDaoConfig.initIdentityScope(type);

        cacheFileDBDao = new CacheFileDBDao(cacheFileDBDaoConfig, this);
        circolareDBDao = new CircolareDBDao(circolareDBDaoConfig, this);
        termineDBDao = new TermineDBDao(termineDBDaoConfig, this);
        newsDBDao = new NewsDBDao(newsDBDaoConfig, this);
        circolareContieneTermineDBDao = new CircolareContieneTermineDBDao(circolareContieneTermineDBDaoConfig, this);
        newsContieneTermineDBDao = new NewsContieneTermineDBDao(newsContieneTermineDBDaoConfig, this);

        registerDao(CacheFileDB.class, cacheFileDBDao);
        registerDao(CircolareDB.class, circolareDBDao);
        registerDao(TermineDB.class, termineDBDao);
        registerDao(NewsDB.class, newsDBDao);
        registerDao(CircolareContieneTermineDB.class, circolareContieneTermineDBDao);
        registerDao(NewsContieneTermineDB.class, newsContieneTermineDBDao);
    }
    
    public void clear() {
        cacheFileDBDaoConfig.getIdentityScope().clear();
        circolareDBDaoConfig.getIdentityScope().clear();
        termineDBDaoConfig.getIdentityScope().clear();
        newsDBDaoConfig.getIdentityScope().clear();
        circolareContieneTermineDBDaoConfig.getIdentityScope().clear();
        newsContieneTermineDBDaoConfig.getIdentityScope().clear();
    }

    public CacheFileDBDao getCacheFileDBDao() {
        return cacheFileDBDao;
    }

    public CircolareDBDao getCircolareDBDao() {
        return circolareDBDao;
    }

    public TermineDBDao getTermineDBDao() {
        return termineDBDao;
    }

    public NewsDBDao getNewsDBDao() {
        return newsDBDao;
    }

    public CircolareContieneTermineDBDao getCircolareContieneTermineDBDao() {
        return circolareContieneTermineDBDao;
    }

    public NewsContieneTermineDBDao getNewsContieneTermineDBDao() {
        return newsContieneTermineDBDao;
    }

}
