package it.gov.fermitivoli.dao;

import it.gov.fermitivoli.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS_CONTIENE_TERMINE_DB.
 */
public class NewsContieneTermineDB {

    private long _id_news;
    private long _id_termine;
    private Long id;
    private long occorrenze;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient NewsContieneTermineDBDao myDao;

    private NewsDB newsDB;
    private Long newsDB__resolvedKey;

    private TermineDB termineDB;
    private Long termineDB__resolvedKey;


    public NewsContieneTermineDB() {
    }

    public NewsContieneTermineDB(Long id) {
        this.id = id;
    }

    public NewsContieneTermineDB(long _id_news, long _id_termine, Long id, long occorrenze) {
        this._id_news = _id_news;
        this._id_termine = _id_termine;
        this.id = id;
        this.occorrenze = occorrenze;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getNewsContieneTermineDBDao() : null;
    }

    public long get_id_news() {
        return _id_news;
    }

    public void set_id_news(long _id_news) {
        this._id_news = _id_news;
    }

    public long get_id_termine() {
        return _id_termine;
    }

    public void set_id_termine(long _id_termine) {
        this._id_termine = _id_termine;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getOccorrenze() {
        return occorrenze;
    }

    public void setOccorrenze(long occorrenze) {
        this.occorrenze = occorrenze;
    }

    /** To-one relationship, resolved on first access. */
    public NewsDB getNewsDB() {
        long __key = this._id_news;
        if (newsDB__resolvedKey == null || !newsDB__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            NewsDBDao targetDao = daoSession.getNewsDBDao();
            NewsDB newsDBNew = targetDao.load(__key);
            synchronized (this) {
                newsDB = newsDBNew;
            	newsDB__resolvedKey = __key;
            }
        }
        return newsDB;
    }

    public void setNewsDB(NewsDB newsDB) {
        if (newsDB == null) {
            throw new DaoException("To-one property '_id_news' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.newsDB = newsDB;
            _id_news = newsDB.getId();
            newsDB__resolvedKey = _id_news;
        }
    }

    /** To-one relationship, resolved on first access. */
    public TermineDB getTermineDB() {
        long __key = this._id_termine;
        if (termineDB__resolvedKey == null || !termineDB__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TermineDBDao targetDao = daoSession.getTermineDBDao();
            TermineDB termineDBNew = targetDao.load(__key);
            synchronized (this) {
                termineDB = termineDBNew;
            	termineDB__resolvedKey = __key;
            }
        }
        return termineDB;
    }

    public void setTermineDB(TermineDB termineDB) {
        if (termineDB == null) {
            throw new DaoException("To-one property '_id_termine' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.termineDB = termineDB;
            _id_termine = termineDB.getId();
            termineDB__resolvedKey = _id_termine;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
