package it.gov.fermitivoli.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEWS_DB.
 */
public class NewsDB {

    private Long id;
    /** Not-null value. */
    private String titolo;
    /** Not-null value. */
    private String link;
    /** Not-null value. */
    private java.util.Date pubDate;
    /** Not-null value. */
    private String testo;
    private String contenuto;
    private String fullimageLink;
    private String thumbimageLink;
    private boolean flagContenutoLetto;
    /** Not-null value. */
    private java.util.Date dataInserimento;

    public NewsDB() {
    }

    public NewsDB(Long id) {
        this.id = id;
    }

    public NewsDB(Long id, String titolo, String link, java.util.Date pubDate, String testo, String contenuto, String fullimageLink, String thumbimageLink, boolean flagContenutoLetto, java.util.Date dataInserimento) {
        this.id = id;
        this.titolo = titolo;
        this.link = link;
        this.pubDate = pubDate;
        this.testo = testo;
        this.contenuto = contenuto;
        this.fullimageLink = fullimageLink;
        this.thumbimageLink = thumbimageLink;
        this.flagContenutoLetto = flagContenutoLetto;
        this.dataInserimento = dataInserimento;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitolo() {
        return titolo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    /** Not-null value. */
    public String getLink() {
        return link;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLink(String link) {
        this.link = link;
    }

    /** Not-null value. */
    public java.util.Date getPubDate() {
        return pubDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPubDate(java.util.Date pubDate) {
        this.pubDate = pubDate;
    }

    /** Not-null value. */
    public String getTesto() {
        return testo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTesto(String testo) {
        this.testo = testo;
    }

    public String getContenuto() {
        return contenuto;
    }

    public void setContenuto(String contenuto) {
        this.contenuto = contenuto;
    }

    public String getFullimageLink() {
        return fullimageLink;
    }

    public void setFullimageLink(String fullimageLink) {
        this.fullimageLink = fullimageLink;
    }

    public String getThumbimageLink() {
        return thumbimageLink;
    }

    public void setThumbimageLink(String thumbimageLink) {
        this.thumbimageLink = thumbimageLink;
    }

    public boolean getFlagContenutoLetto() {
        return flagContenutoLetto;
    }

    public void setFlagContenutoLetto(boolean flagContenutoLetto) {
        this.flagContenutoLetto = flagContenutoLetto;
    }

    /** Not-null value. */
    public java.util.Date getDataInserimento() {
        return dataInserimento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDataInserimento(java.util.Date dataInserimento) {
        this.dataInserimento = dataInserimento;
    }

}
