package it.gov.fermitivoli.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TERMINE_DB.
 */
public class TermineDB {

    private Long id;
    /** Not-null value. */
    private String termine;
    /** Not-null value. */
    private String radice;

    public TermineDB() {
    }

    public TermineDB(Long id) {
        this.id = id;
    }

    public TermineDB(Long id, String termine, String radice) {
        this.id = id;
        this.termine = termine;
        this.radice = radice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTermine() {
        return termine;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTermine(String termine) {
        this.termine = termine;
    }

    /** Not-null value. */
    public String getRadice() {
        return radice;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRadice(String radice) {
        this.radice = radice;
    }

}
